### PR TITLE
Improving code indentation and filtering static fields from domain classes

### PR DESCRIPTION
**Pull request by cleydsonjr**
I've changed changed getDomainProperties method to filter static fields as it don't need to be part of the CRUD.

Also placed the javascripts on main.gsp template at the end of the body

### CODE REVIEW

**Comment by craigburke** [comment]
Awesome! Your changes look really good :+1: 

I'll try to wrap these into a new release sometime next week.

Thanks for the contribution. I really appreciate it.

**Comment by craigburke** [comment]
BTW, the latest version of the test app includes your changes:
http://angular-grails.interwebs.io/

**Comment by cleydsonjr** [comment]
Thats great, I'll keep doing some improvements to the project.

**Comment by craigburke** [comment]
Very very cool! 

If you wouldn't mind throwing an issue up here whenever you start to tackle something particularly meaty it would be appreciated (and I'll start doing the same). I just want to make sure we're not both working on the same things :)

**Comment by cleydsonjr** [comment]
You're right! I'm gonna do that for now on.

**Pull request merged**
